version: "3.8"
services:
  # PHP service
  api_php:
    build: .
    container_name: api_php
    working_dir: /application
    volumes:
      - ./src:/application
    networks:
      - app-network

  #MySQL database service
  api_db:
   image: mysql:5.7
   container_name: mysql-db
   ports:
       - "3306:3306"
   environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: simple_bank_php
       MYSQL_USER: root
       MYSQL_PASSWORD: root
   networks:
       - app-network

  # Nginx service
  api_nginx:
    image: nginx:alpine
    container_name: api_nginx
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ./src:/application
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - api_db
    networks:
      - app-network
networks:
    app-network:
        driver: bridge