version: "3.8"
services:

    # PHP service
    app:
        build: .
        container_name: api_php
        working_dir: /var/www/
        volumes:
            - ./src:/var/www
        networks:
            - app-network

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: api_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: simple_bank_php
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: api_nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
